### ISSUE TITLE
does not seem to work with git version 2.6.1

### ISSUE THREAD

**Issue by stevemao** [scottgonzalez/recursive-blame#10]
```
$ recursive-blame gulp gulpfile.js
/Users/stevemao/.nvm/versions/node/v4.2.1/lib/node_modules/recursive-blame/node_modules/git-tools/git-tools.js:232
				commit: matches[ 1 ],
				               ^

TypeError: Cannot read property '1' of null
    at /Users/stevemao/.nvm/versions/node/v4.2.1/lib/node_modules/recursive-blame/node_modules/git-tools/git-tools.js:232:20
    at Array.map (native)
    at /Users/stevemao/.nvm/versions/node/v4.2.1/lib/node_modules/recursive-blame/node_modules/git-tools/git-tools.js:228:17
    at ChildProcess.<anonymous> (/Users/stevemao/.nvm/versions/node/v4.2.1/lib/node_modules/recursive-blame/node_modules/git-tools/git-tools.js:92:3)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
```

seem like the output of `git blame` is different?

**Comment by scottgonzalez** [comment]
Can you provide the output of `git blame gulpfile.js`?

**Comment by stevemao** [comment]
```
$ git blame gulpfile.babel.js
f13e23bd gulpfile.js       (Sindre Sorhus           2014-06-09 15:02:39 +0200   1) /**
f13e23bd gulpfile.js       (Sindre Sorhus           2014-06-09 15:02:39 +0200   2)  *
ddb5af39 gulpfile.js       (Addy Osmani             2014-06-09 09:56:26 +0100   3)  *  Web Starter Kit
0a02fd91 gulpfile.js       (Addy Osmani             2015-04-27 15:52:06 +0100   4)  *  Copyright 2015 Google Inc. All rights reserved.
f13e23bd gulpfile.js       (Sindre Sorhus           2014-06-09 15:02:39 +0200   5)  *
ddb5af39 gulpfile.js       (Addy Osmani             2014-06-09 09:56:26 +0100   6)  *  Licensed under the Apache License, Version 2.0 (the "License");
ddb5af39 gulpfile.js       (Addy Osmani             2014-06-09 09:56:26 +0100   7)  *  you may not use this file except in compliance with the License.
ddb5af39 gulpfile.js       (Addy Osmani             2014-06-09 09:56:26 +0100   8)  *  You may obtain a copy of the License at
f13e23bd gulpfile.js       (Sindre Sorhus           2014-06-09 15:02:39 +0200   9)  *
2381a601 gulpfile.js       (Arthur Verschaeve       2014-10-22 15:14:09 +0200  10)  *      https://www.apache.org/licenses/LICENSE-2.0
f13e23bd gulpfile.js       (Sindre Sorhus           2014-06-09 15:02:39 +0200  11)  *
ddb5af39 gulpfile.js       (Addy Osmani             2014-06-09 09:56:26 +0100  12)  *  Unless required by applicable law or agreed to in writing, software
ddb5af39 gulpfile.js       (Addy Osmani             2014-06-09 09:56:26 +0100  13)  *  distributed under the License is distributed on an "AS IS" BASIS,
ddb5af39 gulpfile.js       (Addy Osmani             2014-06-09 09:56:26 +0100  14)  *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
```

**Comment by stevemao** [comment]
```
$ git blame gulpfile.js
86bf6fd4 (Steve Mao         2015-11-11 11:46:56 +1100   1) 'use strict';
```

**Comment by stevemao** [comment]
looks like it doesn't work for this particular git project but works for others. so shouldn't have anything to do with git 2.6.1

**Comment by scottgonzalez** [comment]
Does this happen to be an open source repo that I can clone to test against?

**Comment by stevemao** [comment]
I'll find or create one. Sorry I didn't have time to look into it.

**Comment by scottgonzalez** [comment]
No problem. I'm happy to dig in, I just need a test case to work from :-)

**Comment by stevemao** [comment]
Hi @scottgonzalez , it does not work for https://github.com/sindresorhus/dot-prop.

```
$ recursive-blame a package.json
/Users/stevemao/.nvm/versions/node/v4.2.1/lib/node_modules/recursive-blame/node_modules/git-tools/git-tools.js:232
				commit: matches[ 1 ],
				               ^

TypeError: Cannot read property '1' of null
    at /Users/stevemao/.nvm/versions/node/v4.2.1/lib/node_modules/recursive-blame/node_modules/git-tools/git-tools.js:232:20
    at Array.map (native)
    at /Users/stevemao/.nvm/versions/node/v4.2.1/lib/node_modules/recursive-blame/node_modules/git-tools/git-tools.js:228:17
    at ChildProcess.<anonymous> (/Users/stevemao/.nvm/versions/node/v4.2.1/lib/node_modules/recursive-blame/node_modules/git-tools/git-tools.js:92:3)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
```

Don't know if it helps but I have push access to it and my local remotes

```
$ git remote -vv
origin	git@github.com:sindresorhus/dot-prop.git (fetch)
origin	git@github.com:sindresorhus/dot-prop.git (push)
stevemao	git@github.com:stevemao/dot-prop.git (fetch)
stevemao	git@github.com:stevemao/dot-prop.git (push)
```

**Comment by scottgonzalez** [comment]
I can't reproduce this:

```
dot-prop (master) $ node -v
v4.2.1
dot-prop (master) $ recursive-blame a package.json



1) {
2)   "name": "dot-prop",
3)   "version": "2.2.0",
4)   "description": "Get or set a property from a nested object using a dot path",
5)   "license": "MIT",
6)   "repository": "sindresorhus/dot-prop",

Next action [r,n,p,c,d,q,?]? q
```

**Comment by scottgonzalez** [comment]
If we can't figure out a way for me to create a reproduction case, would you be interested in finding a time that we're both available to do a screen share and track down the issue?

**Comment by stevemao** [comment]
Yes. When I have time :)
