### ISSUE TITLE
Error: fatal: bad revision

### ISSUE THREAD

**Issue by Jellyfrog** [scottgonzalez/recursive-blame#16]
```
{ Error: fatal: bad revision '^06a7871^'

    at ChildProcess.<anonymous> (/usr/lib/node_modules/recursive-blame/node_modules/spawnback/index.js:31:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12) code: 128 }
``` 

To reproduce:

1. sudo npm install -g recursive-blame
2. git clone https://github.com/scottgonzalez/recursive-blame.git
3. cd recursive-blame
4. git recursive-blame var index.js
5. press r
6. press r
7. error like above

``` 
$ node -v
v6.10.3

$ git --version
git version 2.14.1
```

**Comment by Jellyfrog** [comment]
Ah, ops, just saw #5
